In [15]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [31]:
s1=np.random.randint(1,800,500)
s1

array([ 24, 363, 239, 217, 620, 545, 490, 101, 246, 486, 745, 564, 581,
       343, 249, 371, 662, 222, 785,  51, 313, 751, 464, 340,  13, 685,
        53, 575, 348, 532, 777, 567, 434,  55, 189, 503, 482, 438, 109,
       675, 671, 517, 269, 302, 333, 174, 654,   1, 750, 376, 442, 272,
       166, 272, 359, 549, 513, 243, 447, 778, 318, 144, 241, 694,  42,
       638, 494, 266, 387, 238, 308,  69, 264, 167, 744, 254, 497, 406,
       515, 190, 161, 736, 562, 564, 179,  58, 255, 683,  95, 176,  90,
       611, 505, 340, 120, 387, 230, 287, 385, 485, 603, 353, 620, 368,
       794,  80,  88, 593, 184,  43, 384, 103, 371, 414, 371, 121,  92,
       602, 440, 135, 506, 710,   9, 152, 690,  56, 503,  12, 679, 356,
       202, 156, 150, 435, 225, 539, 524, 525, 255, 133, 114, 288, 190,
       209, 700,  69, 289, 780, 684, 728, 414, 764, 231,  92, 338, 110,
       649,  40, 571,  46, 236, 211,  38, 687, 357, 783, 354, 308, 732,
       167, 447,   7, 138, 415,   5, 700, 158,  24, 245, 787, 40

In [33]:
s3=np.random.randint(1,4,500,dtype=int)
s3

array([3, 2, 1, 3, 3, 2, 2, 3, 2, 3, 3, 3, 2, 3, 2, 1, 1, 1, 3, 2, 3, 3,
       3, 1, 2, 2, 2, 3, 2, 2, 2, 3, 2, 3, 2, 2, 1, 2, 2, 2, 2, 1, 3, 3,
       3, 1, 2, 3, 3, 1, 1, 2, 1, 2, 3, 1, 1, 3, 2, 2, 2, 1, 3, 3, 2, 3,
       3, 3, 2, 3, 3, 3, 1, 3, 1, 3, 2, 3, 2, 1, 1, 2, 1, 3, 2, 1, 2, 1,
       3, 1, 3, 3, 3, 1, 3, 2, 1, 2, 3, 1, 2, 1, 2, 2, 1, 3, 3, 1, 1, 1,
       3, 2, 2, 3, 3, 1, 1, 1, 2, 3, 1, 3, 3, 1, 3, 2, 3, 3, 1, 1, 2, 1,
       2, 1, 2, 1, 1, 2, 1, 2, 3, 3, 2, 3, 2, 1, 2, 2, 3, 2, 3, 1, 2, 2,
       3, 2, 2, 3, 1, 1, 3, 3, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 3,
       2, 1, 3, 3, 2, 2, 1, 1, 3, 3, 2, 1, 3, 3, 1, 2, 2, 1, 2, 2, 1, 3,
       1, 3, 2, 2, 2, 3, 2, 1, 3, 3, 1, 1, 3, 2, 3, 1, 3, 1, 3, 1, 2, 1,
       2, 2, 3, 3, 3, 3, 3, 2, 3, 2, 3, 2, 3, 1, 2, 1, 2, 3, 1, 2, 3, 1,
       3, 3, 3, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 3, 1, 2, 3, 1, 1, 2, 2,
       2, 2, 2, 1, 2, 1, 2, 2, 3, 1, 2, 1, 2, 1, 2, 3, 3, 3, 3, 2, 1, 2,
       3, 1, 2, 3, 2, 3, 1, 2, 1, 1, 2, 1, 1, 2, 1,

In [36]:
data1={"Value":s1,"state":s3}
df2=pd.DataFrame(data1)
df2


Value  state
0       24      3
1      363      2
2      239      1
3      217      3
4      620      3
..     ...    ...
495    613      1
496    157      3
497    449      3
498    768      1
499    749      3

[500 rows x 2 columns]

In [40]:
df2["new_state"]=[1 if x<50 else 2 for x in df2["Value"] ]
df2

Value  state  new_state
0       24      3          1
1      363      2          2
2      239      1          2
3      217      3          2
4      620      3          2
..     ...    ...        ...
495    613      1          2
496    157      3          2
497    449      3          2
498    768      1          2
499    749      3          2

[500 rows x 3 columns]

In [4]:
data={"Score":[35,90,78,67,90,90,67,56,45,90,78,80,77,43,90,19,889,665,888,39,56,61,65],
     "Status":[1,2,2,2,2,2,2,2,1,2,2,2,2,1,2,1,3,3,3,1,2,2,2]}

In [5]:
df=pd.DataFrame(data)

In [6]:
df

Score  Status
0      35       1
1      90       2
2      78       2
3      67       2
4      90       2
5      90       2
6      67       2
7      56       2
8      45       1
9      90       2
10     78       2
11     80       2
12     77       2
13     43       1
14     90       2
15     19       1
16    889       3
17    665       3
18    888       3
19     39       1
20     56       2
21     61       2
22     65       2

In [20]:
M=KNeighborsClassifier()

In [11]:
X=df.drop("Status",axis=1)
Y=df["Status"]

In [17]:
Xtr,Xte,Ytr,Yte=train_test_split(X,Y,train_size=0.75,random_state=10)

In [21]:
M.fit(Xtr,Ytr)

KNeighborsClassifier()

In [26]:
M.predict([[700]])

array([3], dtype=int64)